# Generated by Django 4.0.4 on 2022-07-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='collection_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='description',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
